### ISSUE TITLE
Inclusão da Calculadora

### ISSUE THREAD

**Issue by GuilhermePreussler** [rikamishiro/projeto-bootstrap4#5]

**Comment by GuilhermePreussler** [comment]
Inclusão da calculadora como uma nova ferramento no projeto possibilitando o usuário a realizar calculos matemáticos básicos.

**Comment by guipreussler** [comment]
Protótipos da calculadora:

![prototipo_2](https://github.com/rikamishiro/projeto-bootstrap4/assets/26905661/a442797c-b3d4-420c-9b9e-647812e09cff)

![prototipo_3](https://github.com/rikamishiro/projeto-bootstrap4/assets/26905661/d565bc7e-7dce-424c-8481-14b752ccfdb8)

**Comment by GuilhermePreussler** [comment]
Protótipos da calculadora:

![prototipo_2](https://github.com/rikamishiro/projeto-bootstrap4/assets/133717606/12e0355c-9414-44a7-a9cd-4e016606c48f)
